---
apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    kubernetes.io/metadata.name: app
    environment: dev
    security-tier: application

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    kubernetes.io/metadata.name: monitoring

---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    kubernetes.io/metadata.name: external-secrets

---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    kubernetes.io/metadata.name: kyverno
