---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/cse-pa-final-dev-external-secrets-role
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/component: backend

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/cse-pa-final-dev-external-secrets-role

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/cse-pa-final-dev-lb-controller-role

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-deployer
  namespace: kube-system
  automountServiceAccountToken: false
