---
# External Secrets Operator — SecretStore pointing to AWS Secrets Manager
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: app
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: app-sa

---
# SecretStore for SSM Parameter Store
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-ssm-parameter-store
  namespace: app
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: app-sa
